// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmpcK1TysxlF7EEEB9o-ooD14rAGwQrs',
    appId: '1:957459349618:web:c3f11687fc00c8104e82eb',
    messagingSenderId: '957459349618',
    projectId: 'energyapp-776d5',
    authDomain: 'energyapp-776d5.firebaseapp.com',
    storageBucket: 'energyapp-776d5.firebasestorage.app',
    measurementId: 'G-SRVWVQY2B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1PLz7IDaIwAIPk8uvwXbtcIborT4VzcQ',
    appId: '1:957459349618:android:33d497bc74373f834e82eb',
    messagingSenderId: '957459349618',
    projectId: 'energyapp-776d5',
    storageBucket: 'energyapp-776d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDAJD-Nwf_HFYLqKdTyyBs7i4zBEoxi_w',
    appId: '1:957459349618:ios:c2a35b8cef83cb8e4e82eb',
    messagingSenderId: '957459349618',
    projectId: 'energyapp-776d5',
    storageBucket: 'energyapp-776d5.firebasestorage.app',
    iosBundleId: 'com.example.energyApp',
  );
}
